exports.seed = async (knex) => {
    await knex('products').del();

    await knex('products').insert([
        {
            name: "VIVO",
            name_slug: "vivo",
            image: "/uploads/vivo.jpg",
            description: "Vivo 5G Charger in the Box (Lily White, 128 GB)  (6 GB RAM)",
            marked_price: 10000.00,
            purchased_price: 7000.00,
            selling_price: 8000.00,
            category: 2,
            unit_type: 3,
            min_quantity: 5,
            is_active: true,
            is_delete: false,
            ratings: "5",
            reviews: "Its good",
        },
        {
            name: "OPPO",
            name_slug: "oppo",
            image: "/uploads/oppo.jpg",
            description: "Oppo 5G Charger in the Box (Lily White, 128 GB)  (6 GB RAM)",
            marked_price: 15000.00,
            purchased_price: 10000.00,
            selling_price: 12000.00,
            category: 2,
            unit_type: 3,
            min_quantity: 5,
            is_active: true,
            is_delete: false,
            ratings: "3",
            reviews: "Its average",
        },
        {
            name: "ACER",
            name_slug: "acer",
            image: "/uploads/acer.jpg",
            description: "Acer 5G Charger in the Box (Lily White, 128 GB)  (6 GB RAM)",
            marked_price: 50000.00,
            purchased_price: 47000.00,
            selling_price: 49000.00,
            category: 3,
            unit_type: 3,
            min_quantity: 7,
            is_active: true,
            is_delete: false,
            ratings: "4",
            reviews: "Its good",
        },
        {
            name: "PC",
            name_slug: "pc",
            image: "/uploads/pc.jpg",
            description: "PC 5G Charger in the Box (Lily White, 128 GB)  (6 GB RAM)",
            marked_price: 80000.00,
            purchased_price: 70000.00,
            selling_price: 79000.00,
            category: 4,
            unit_type: 3,
            min_quantity: 3,
            is_active: true,
            is_delete: false,
            ratings: "2",
            reviews: "Its good",
        },
        {
            name: "NOKIA",
            name_slug: "nokia",
            image: "/uploads/nokia.jpg",
            description: "nokia is a mobile phone",
            marked_price: 1000.00,
            purchased_price: 500.00,
            selling_price: 800.00,
            category: 1,
            unit_type: 3,
            min_quantity: 15,
            is_active: true,
            is_delete: false,
            ratings: "5",
            reviews: "Its good",
        }
    ]);
}